### ISSUE TITLE
Autorun allows infinite Elytra flight

### ISSUE THREAD

**Issue by Darkere** [Lothrazar/AutoRun#1]
Toggling autorun allows me to fly infinitely with the elytra. 

autorun-1.14.4-1.0.5
forge 28.1.87

**Comment by Lothrazar** [comment]
Thanks for report, i know it was a long time ago.  Reviving this dead mod, at least for 1.16.  Added a config to disable using this while flying with elytra https://www.curseforge.com/minecraft/mc-mods/auto-sprint/files/3183048
