### ISSUE TITLE
autorun doesn't reduce hunger

### ISSUE THREAD

**Issue by TheUntamed** [Lothrazar/AutoRun#2]
The Titel says it all
mc 1.14.4
reproducible

**Comment by Lothrazar** [comment]
This is kind of by design. But anyway, fixed in minecraft 1.16, i set player.isSprinting(true) which then triggers the Exhaustion stat to drain, which indirectly affects hunger https://www.curseforge.com/minecraft/mc-mods/auto-sprint/files/3183048
