### ISSUE TITLE
[1.15.2] Client side only?

### ISSUE THREAD

**Issue by TheUntamed** [Lothrazar/AutoRun#4]
Just a question: Is this mod client side only?

**Comment by Lothrazar** [comment]
Its not currently client side only.  But this week i will be attempting to make the 1.16 build client only. if possible. if it works I will note it on the curseforge page

**Comment by Lothrazar** [comment]
this version functions client-only https://www.curseforge.com/minecraft/mc-mods/auto-sprint/files/3183048
