### ISSUE TITLE
Very slow when using a boat (at least half speed, maybe slower)

### ISSUE THREAD

**Issue by Crystallyne** [Lothrazar/AutoRun#5]
Minecraft Version: 1.16.3

Forge Version: 

Mod Version: 1.16.3-1.0.5

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

When using a boat, the player moves very slowly. At least half the speed of what you get if you just hold down the W key to move forward. (Moving forward using the W key like normal works at normal speed, it's only when using the hot key for this mod that it moves so slowly.)

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Fixed in 1.16 here. Also new config file exists https://www.curseforge.com/minecraft/mc-mods/auto-sprint/files/3183048
